// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: model/message.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define an enumeration for message types (e.g., New Order, Cancel Order)
type MsgType int32

const (
	MsgType_UNKNOWN          MsgType = 0
	MsgType_NEW_ORDER        MsgType = 1 // New order - Single
	MsgType_CANCEL_ORDER     MsgType = 2 // Order Cancel Request
	MsgType_EXECUTION_REPORT MsgType = 3 // Execution Report
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NEW_ORDER",
		2: "CANCEL_ORDER",
		3: "EXECUTION_REPORT",
	}
	MsgType_value = map[string]int32{
		"UNKNOWN":          0,
		"NEW_ORDER":        1,
		"CANCEL_ORDER":     2,
		"EXECUTION_REPORT": 3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_model_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_model_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_model_message_proto_rawDescGZIP(), []int{0}
}

// Define an enumeration for order sides
type Side int32

const (
	Side_BUY  Side = 0
	Side_SELL Side = 1
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	Side_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_model_message_proto_enumTypes[1].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_model_message_proto_enumTypes[1]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_model_message_proto_rawDescGZIP(), []int{1}
}

// Define an enumeration for order statuses
type OrdStatus int32

const (
	OrdStatus_NEW              OrdStatus = 0
	OrdStatus_PARTIALLY_FILLED OrdStatus = 1
	OrdStatus_FILLED           OrdStatus = 2
	OrdStatus_CANCELED         OrdStatus = 3
)

// Enum value maps for OrdStatus.
var (
	OrdStatus_name = map[int32]string{
		0: "NEW",
		1: "PARTIALLY_FILLED",
		2: "FILLED",
		3: "CANCELED",
	}
	OrdStatus_value = map[string]int32{
		"NEW":              0,
		"PARTIALLY_FILLED": 1,
		"FILLED":           2,
		"CANCELED":         3,
	}
)

func (x OrdStatus) Enum() *OrdStatus {
	p := new(OrdStatus)
	*p = x
	return p
}

func (x OrdStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrdStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_model_message_proto_enumTypes[2].Descriptor()
}

func (OrdStatus) Type() protoreflect.EnumType {
	return &file_model_message_proto_enumTypes[2]
}

func (x OrdStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrdStatus.Descriptor instead.
func (OrdStatus) EnumDescriptor() ([]byte, []int) {
	return file_model_message_proto_rawDescGZIP(), []int{2}
}

// Define the structure of a ContraBroker repeating group
type ContraBrokerGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContraBroker    string `protobuf:"bytes,1,opt,name=contra_broker,json=contraBroker,proto3" json:"contra_broker,omitempty"`            // ContraBroker (Tag 375)
	ContraTrader    string `protobuf:"bytes,2,opt,name=contra_trader,json=contraTrader,proto3" json:"contra_trader,omitempty"`            // ContraTrader (Tag 337)
	ContraTradeQty  string `protobuf:"bytes,3,opt,name=contra_trade_qty,json=contraTradeQty,proto3" json:"contra_trade_qty,omitempty"`    // ContraTradeQty (Tag 437)
	ContraTradeTime string `protobuf:"bytes,4,opt,name=contra_trade_time,json=contraTradeTime,proto3" json:"contra_trade_time,omitempty"` // ContraTradeTime (Tag 438)
}

func (x *ContraBrokerGroup) Reset() {
	*x = ContraBrokerGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContraBrokerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContraBrokerGroup) ProtoMessage() {}

func (x *ContraBrokerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_model_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContraBrokerGroup.ProtoReflect.Descriptor instead.
func (*ContraBrokerGroup) Descriptor() ([]byte, []int) {
	return file_model_message_proto_rawDescGZIP(), []int{0}
}

func (x *ContraBrokerGroup) GetContraBroker() string {
	if x != nil {
		return x.ContraBroker
	}
	return ""
}

func (x *ContraBrokerGroup) GetContraTrader() string {
	if x != nil {
		return x.ContraTrader
	}
	return ""
}

func (x *ContraBrokerGroup) GetContraTradeQty() string {
	if x != nil {
		return x.ContraTradeQty
	}
	return ""
}

func (x *ContraBrokerGroup) GetContraTradeTime() string {
	if x != nil {
		return x.ContraTradeTime
	}
	return ""
}

// Define the structure of a FIX message
type FIXMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderCompId string  `protobuf:"bytes,1,opt,name=sender_comp_id,json=senderCompId,proto3" json:"sender_comp_id,omitempty"` // SenderCompID (Tag 49)
	TargetCompId string  `protobuf:"bytes,2,opt,name=target_comp_id,json=targetCompId,proto3" json:"target_comp_id,omitempty"` // TargetCompID (Tag 56)
	MsgSeqNum    int32   `protobuf:"varint,3,opt,name=msg_seq_num,json=msgSeqNum,proto3" json:"msg_seq_num,omitempty"`         // MsgSeqNum (Tag 34)
	MsgType      MsgType `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3,enum=MsgType" json:"msg_type,omitempty"`    // MsgType (Tag 35)
	SendingTime  string  `protobuf:"bytes,5,opt,name=sending_time,json=sendingTime,proto3" json:"sending_time,omitempty"`      // SendingTime (Tag 52)
	// New Order - Single specific fields
	ClOrdId      string  `protobuf:"bytes,6,opt,name=cl_ord_id,json=clOrdId,proto3" json:"cl_ord_id,omitempty"`               // ClOrdID (Tag 11)
	Symbol       string  `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`                                  // Symbol (Tag 55)
	Side         Side    `protobuf:"varint,8,opt,name=side,proto3,enum=Side" json:"side,omitempty"`                           // Side (Tag 54)
	OrderQty     float64 `protobuf:"fixed64,9,opt,name=order_qty,json=orderQty,proto3" json:"order_qty,omitempty"`            // OrderQty (Tag 38)
	Price        float64 `protobuf:"fixed64,10,opt,name=price,proto3" json:"price,omitempty"`                                 // Price (Tag 44)
	TransactTime string  `protobuf:"bytes,11,opt,name=transact_time,json=transactTime,proto3" json:"transact_time,omitempty"` // TransactTime (Tag 60)
	// Execution Report specific fields
	ExecId    string    `protobuf:"bytes,12,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`                          // ExecID (Tag 17)
	OrdStatus OrdStatus `protobuf:"varint,13,opt,name=ord_status,json=ordStatus,proto3,enum=OrdStatus" json:"ord_status,omitempty"` // OrdStatus (Tag 39)
	LastQty   float64   `protobuf:"fixed64,14,opt,name=last_qty,json=lastQty,proto3" json:"last_qty,omitempty"`                     // LastQty (Tag 32)
	LastPrice float64   `protobuf:"fixed64,15,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`               // LastPx (Tag 31)
	// Repeating group for ContraBrokers
	ContraBrokers []*ContraBrokerGroup `protobuf:"bytes,16,rep,name=contra_brokers,json=contraBrokers,proto3" json:"contra_brokers,omitempty"` // NoContraBrokers (Tag 382)
}

func (x *FIXMessage) Reset() {
	*x = FIXMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FIXMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIXMessage) ProtoMessage() {}

func (x *FIXMessage) ProtoReflect() protoreflect.Message {
	mi := &file_model_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIXMessage.ProtoReflect.Descriptor instead.
func (*FIXMessage) Descriptor() ([]byte, []int) {
	return file_model_message_proto_rawDescGZIP(), []int{1}
}

func (x *FIXMessage) GetSenderCompId() string {
	if x != nil {
		return x.SenderCompId
	}
	return ""
}

func (x *FIXMessage) GetTargetCompId() string {
	if x != nil {
		return x.TargetCompId
	}
	return ""
}

func (x *FIXMessage) GetMsgSeqNum() int32 {
	if x != nil {
		return x.MsgSeqNum
	}
	return 0
}

func (x *FIXMessage) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_UNKNOWN
}

func (x *FIXMessage) GetSendingTime() string {
	if x != nil {
		return x.SendingTime
	}
	return ""
}

func (x *FIXMessage) GetClOrdId() string {
	if x != nil {
		return x.ClOrdId
	}
	return ""
}

func (x *FIXMessage) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FIXMessage) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_BUY
}

func (x *FIXMessage) GetOrderQty() float64 {
	if x != nil {
		return x.OrderQty
	}
	return 0
}

func (x *FIXMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *FIXMessage) GetTransactTime() string {
	if x != nil {
		return x.TransactTime
	}
	return ""
}

func (x *FIXMessage) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *FIXMessage) GetOrdStatus() OrdStatus {
	if x != nil {
		return x.OrdStatus
	}
	return OrdStatus_NEW
}

func (x *FIXMessage) GetLastQty() float64 {
	if x != nil {
		return x.LastQty
	}
	return 0
}

func (x *FIXMessage) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *FIXMessage) GetContraBrokers() []*ContraBrokerGroup {
	if x != nil {
		return x.ContraBrokers
	}
	return nil
}

var File_model_message_proto protoreflect.FileDescriptor

var file_model_message_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x54, 0x72, 0x61, 0x64, 0x65, 0x51, 0x74, 0x79, 0x12,
	0x2a, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xa0, 0x04, 0x0a, 0x0a,
	0x46, 0x49, 0x58, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x73, 0x65,
	0x71, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x73, 0x67,
	0x53, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x23, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x09, 0x63, 0x6c, 0x5f, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x19, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x05, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x73, 0x69, 0x64, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x65, 0x63, 0x49, 0x64, 0x12, 0x29,
	0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x4f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09,
	0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x6c, 0x61, 0x73,
	0x74, 0x51, 0x74, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x5f, 0x62, 0x72,
	0x6f, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x73, 0x2a, 0x4d,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x45, 0x57, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x58, 0x45, 0x43, 0x55,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x03, 0x2a, 0x19, 0x0a,
	0x04, 0x53, 0x69, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x55, 0x59, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x53, 0x45, 0x4c, 0x4c, 0x10, 0x01, 0x2a, 0x44, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x45, 0x57, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x50, 0x41, 0x52, 0x54, 0x49, 0x41, 0x4c, 0x4c, 0x59, 0x5f, 0x46, 0x49, 0x4c, 0x4c,
	0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x49, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_model_message_proto_rawDescOnce sync.Once
	file_model_message_proto_rawDescData = file_model_message_proto_rawDesc
)

func file_model_message_proto_rawDescGZIP() []byte {
	file_model_message_proto_rawDescOnce.Do(func() {
		file_model_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_message_proto_rawDescData)
	})
	return file_model_message_proto_rawDescData
}

var file_model_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_model_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_message_proto_goTypes = []any{
	(MsgType)(0),              // 0: MsgType
	(Side)(0),                 // 1: Side
	(OrdStatus)(0),            // 2: OrdStatus
	(*ContraBrokerGroup)(nil), // 3: ContraBrokerGroup
	(*FIXMessage)(nil),        // 4: FIXMessage
}
var file_model_message_proto_depIdxs = []int32{
	0, // 0: FIXMessage.msg_type:type_name -> MsgType
	1, // 1: FIXMessage.side:type_name -> Side
	2, // 2: FIXMessage.ord_status:type_name -> OrdStatus
	3, // 3: FIXMessage.contra_brokers:type_name -> ContraBrokerGroup
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_model_message_proto_init() }
func file_model_message_proto_init() {
	if File_model_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ContraBrokerGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FIXMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_message_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_message_proto_goTypes,
		DependencyIndexes: file_model_message_proto_depIdxs,
		EnumInfos:         file_model_message_proto_enumTypes,
		MessageInfos:      file_model_message_proto_msgTypes,
	}.Build()
	File_model_message_proto = out.File
	file_model_message_proto_rawDesc = nil
	file_model_message_proto_goTypes = nil
	file_model_message_proto_depIdxs = nil
}
